version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: exo12
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: product

volumes:
  mongo_data:
    driver: local


# docker-compose up -d